email:
  subject_template: "Daily Newspaper - {{ date }}"
  recipients:
    - "your-email@example.com"
    # Add more recipients as needed

cloud_storage:
  provider: "R2"  # "R2" or "S3"
  bucket_name: "your-newspaper-bucket"
  
  # For R2 (Cloudflare)
  r2_account_id: "your-account-id"
  r2_access_key_id: "your-access-key"
  r2_secret_access_key: "your-secret-key"
  r2_public_url_prefix: "https://your-public-url-prefix.r2.dev"
  
  # For S3 (AWS)
  s3_access_key_id: "your-access-key"
  s3_secret_access_key: "your-secret-key"
  s3_region: "us-east-1"
  s3_public_url_prefix: "https://your-bucket.s3.amazonaws.com"

newspaper:
  url: "https://your-newspaper-website.com"
  username: "your-username"
  password: "your-password"
  download_page: ""  # Optional: Only if different from login page
  download_link_selector: ""  # Optional: CSS selector for download link

email_service:
  provider: "sendgrid"  # "sendgrid" or "mailgun"
  sender: "your-sender@example.com"
  
  # For SendGrid
  sendgrid_api_key: "your-api-key"
  
  # For Mailgun
  mailgun_api_key: "your-api-key"
  mailgun_domain: "your-domain" 